name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake configure with asan checks
      run: cmake -B build -DCMAKE_BUILD_TYPE=SanitizeAddress
    - name: make with asan checks
      run: make -C build
    - name: make check
      run: make -C build check
